#{% set data = load_setup_py_data() %}
{% set version = "0.0.5" %}


package:
  name: emcore
  version: {{ version }}

source:
  #git_url: git@github.com:3dem/emcore.git
  #path: /home/josem/work/development/emcore
  path: ../../../../emcore
  
build:
  number: 0

requirements:
  build:
    - cmake >=3.0
    - {{ compiler('cxx') }}
    - make
    - scikit-build
  host:
    - python {{ python }}
    - libpng
    - libtiff
    - jpeg
    - freetype
    - fftw >3.0
    - sqlite >3.0
    - scikit-build
    - numpy
  run:
    - python
    - jpeg
    - libpng
    - freetype
    - libtiff
    - fftw >3.0
    - sqlite >3.0
    - numpy
    
test:
   imports:
     - emcore
   commands:
     - python -m emcore.tests

about:
  home: https://github.com/3dem/emcore
  license: GPLv3
  summary: Basic image processing library for Electron Microscopy

extra:
  recipe-maintainers:
    - delarosatrevin

