FROM dockcross/manylinux2010-x64

LABEL description="manylinux image from drockcross to build emcore wheels"
LABEL maintainer="J.M. de la Rosa Trevin delarosatrevin@gmail.com"


RUN yum install -y libtiff-devel libpng-devel libjpeg-devel fftw3-devel sqlite-devel


